### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

###
POST http://localhost:8080/api/users/register
Content-Type: application/json

{
  "username": "dat132",
  "password": "Abc@12345",
  "email": "dat132@example.com",
  "gender": "MALE",
  "phoneNumber": "0909999999",
  "DoB": "2000-01-01"
}

###Admin login
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "username": "dat132",
  "password": "Abc@12345"
}

###User login
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "username": "user123",
  "password": "Abc@12345"
}

###
POST http://localhost:8080/api/admin/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJkYXQxMzIiLCJpYXQiOjE3NDkxOTc3ODcsImV4cCI6MTc0OTIwMTM4Nywicm9sZSI6IlJPTEVfQURNSU4iLCJ1c2VybmFtZSI6ImRhdDEzMiJ9.lenzVt1xZEcfLBl7Ieij-1TyQRhPgs8wfLGjlAkn67Q

{
  "username": "test132",
  "password": "Test@12345",
  "email": "testadmin@example.com",
  "role": "ROLE_ADMIN"
}

###
POST http://localhost:8080/api/auth/refresh
X-Refresh-Token: 940d89fb-cdc0-4a19-97fa-954493c8881c