spring:
  datasource:
    url: jdbc:mysql://localhost:3306/movie_booker
    username: root
    password: Tu100den10
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 20
          fetch_size: 50
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: movie_booking_group
      auto-offset-reset: earliest
  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration

jwt:
  secret: c2Rxd2QxMzFlMTJZVCM2ITE4NzcqKigpJQ==
  expiration: 3600000 # 1 hour in milliseconds
  refresh-token-expiration: 604800000 # 7 days

logging:
  level:
    org.springframework.security: DEBUG
