spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:update}
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 20
          fetch_size: 50

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP}
    consumer:
      group-id: ${KAFKA_GROUP_ID:movie_booking_group}
      auto-offset-reset: earliest

  data:
    redis:
      host: ${REDIS_HOST:127.0.0.1}
      port: ${REDIS_PORT:6379}

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USER}
    password: ${MAIL_PASS}
    properties.mail.smtp:
      auth: true
      starttls.enable: true

cloudinary:
  cloud-name: ${CLOUD_NAME}
  api-key: ${CLOUD_API_KEY}
  api-secret: ${CLOUD_API_SECRET}

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXP:3600000}
  refresh-token-expiration: ${JWT_REFRESH_EXP:604800000}

vnpay:
  tmn-code: ${VNP_TMN}
  hash-secret: ${VNP_HASH}
  pay-url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
  return-url: http://localhost:5173/vnpay-return
logging:
  level:
    org.springframework.web.socket.server: DEBUG
    org.springframework.web.socket.handler: DEBUG
    org.springframework.web.socket.config: DEBUG
    org.springframework.messaging.simp: DEBUG
    org.springframework.messaging.simp.user: DEBUG
    org.springframework.messaging.simp.stomp: DEBUG
gotit:
  authorization-key: ${GOTIT_AUTHORIZATION_KEY}